version: '3.8'
services:
  producer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "producer"
    volumes:
      - ./2017-citibike-tripdata:/app/data:ro
    stdin_open: true
    tty: true
    command: ["python" , "src/produce.py"]
    depends_on:
      - redis
      - consumer

  consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "consumer"
    volumes:
      - ./matches:/app/matches:wo
    stdin_open: true
    tty: true 
    command: ["python", "src/consume.py"]     
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
